/**
 * storage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FileCreateStartBody } from '../models/FileCreateStartBody';
import { R2UploadedPartBody } from '../models/R2UploadedPartBody';
import { Visibility } from '../models/Visibility';
import { HttpFile } from '../http/http';

export class FilesPostRequest {
    'key'?: string;
    'visibility'?: Visibility;
    'parts'?: R2UploadedPartBody[];

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "Visibility",
            "format": ""
        },
        {
            "name": "parts",
            "baseName": "parts",
            "type": "R2UploadedPartBody[]",
            "format": ""
        }    
    ];

    static getAttributeTypeMap() {
        return FilesPostRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



