/**
 * storage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { R2Object } from '../models/R2Object';
import { HttpFile } from '../http/http';

export class R2ObjectList {
    'objects'?: Array<R2Object>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "objects",
            "baseName": "objects",
            "type": "Array<R2Object>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return R2ObjectList.attributeTypeMap;
    }

    public constructor() {
    }
}

