name = "storage"
main = "src/api_entry.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-03-20"
account_id="asdfasdfasdfasdfasdf"
workers_dev = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'asdfasdfasdf'

[[d1_databases]]
binding = "DB" # This will be how you refer to your database in your Worker
database_name = "adsfasdfasdfb"
database_id = "asdfasdfasdf"

[[kv_namespaces]]
binding='SIGNED_URL_KEYS'
id='asdfasdfasdfasdfasdf'

[vars]
SECRET = "--------" #must be same as app secret in stateless auth